docs/files.txt
docs/logging.txt
docs/streams.txt
testfixtures/logcapture.py
testfixtures/outputcapture.py
testfixtures/tempdirectory.py
testfixtures/tests/test_tempdir.py

Use explicit expected/actual for internal calls to `compare()` in:
* `LogCapture.check()`
* `OutputCapture.compare()`
* `TempDirectory.compare()`
Fixes #26

Use explicit expected/actual for internal calls to compare()

---

testfixtures/compat.py
testfixtures/tests/test_outputcapture.py

@cjw296 
First, thanks for the awesome tool.
I encountered errors such as the following.
```
from testfixtures import OutputCapture
with OutputCapture() as output:
print(u"こんにちわ")
```
error
```
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)
```
The cause of this error is because cStringIO cannot handle some Unicode strings well.
see also https://docs.python.org/2.7/library/stringio.html?highlight=cstringio#module-cStringIO
I have changed cStringIO to StringIO. Please feel free to merge it.

cStringIO cannot handle some Unicode strings.

---

testfixtures/replace.py

Since testfixtures v4.8, PyPy v4.0.1 would break with `TypeError` instead of `AttributeError` (see [this](https://travis-ci.org/nicolaiarocci/eve/jobs/111175613) Travis build). According to [this](https://bitbucket.org/pypy/pypy/issues/1108/cpyext-typeerror-instead-of-attributeerror) comment by Armin Rigo, PyPy will sometimes raise TypeError whereas CPython raises `AttributeError`.
This patch allows PyPy v4.0.1 (Python 2.7.10) to run the tests without issues.

Fix: running tests with PyPy v4.0.1 breaks the build with TypeError

---

testfixtures/tempdirectory.py

Thanks a lot for making `testfixtures` available! :)
This PR adds a couple of comments clarifying the behaviour of `TempDirectory.compare()`. I'm not sure if it's intended behaviour that the comparison fails if the argument `expected` is not sorted but at least it's good to document this.

Clarify behaviour of TempDirectory.compare()

---

README.rst

just a minor annoyance with coveralls badge.  here's a before/after .gif for this change:

better status images for github landing page

---

docs/conf.py

Whilst working on the Reproducible Builds effort [0], we noticed
that python-testfixtures could not be built reproducibly.
[0] https://reproducible-builds.org/
This issue was originally filed in Debian here: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=853912

Make the documentation reproducible.

---

docs/popen.txt
setup.py
testfixtures/popen.py
testfixtures/tests/test_popen.py
testfixtures/tests/test_popen_docs.py

Sometimes I need to test calling a command which will have different output each time, typically polling the status of some external system.  Currently this isn't possible.
By allowing setting a callable to be called when the command is actually run, it's possible to achieve this.
One potential concern here are the errors if the specified callable has the wrong signature or returns the wrong number of parameters to be unpacked.  I think the default errors are clear enough here.
Happy to extend tests and doc if needed.

Allow setting callable for popen behaviour

---

docs/logging.txt
testfixtures/logcapture.py
testfixtures/tests/test_logcapture.py

Putting this up here to think about where to go with this.
This was spurred on by #70 , but a couple of people have also asked about this kind of thing and I'd like to offer a bit more flexibility than `.check()` currently does.
So, options:
- Is `.actual()` being part of the public api enough, and then people can make whatever assertions they like?
- Finish off the `compare()` method as it currently is, `present=None` means an exact check, `present=True` means make sure the expected are present, order unimportant if expressed as a set or single log row, order matches as a chunk if expected supplied as a list.
- Have a `compare()` but also one method to assert messages are present, one to assert messages are not present.
@asqui @wimglenn @nebulans - looking for feedback from you guys!

Logcapture compare

---

docs/api.txt
docs/popen.txt
testfixtures/compat.py
testfixtures/popen.py
testfixtures/tests/test_popen.py
testfixtures/tests/test_popen_docs.py

This will fix #90 but still to do:
- fix `mock.call`: https://bugs.python.org/issue35226 - which will mean a fix in testfixtures in the meantime.
- fix PRs to testfixtures so that coverage checks work as required.
- update `MockPopen` docs to recommend using `all_calls` or a process' `calls` when checking what was called.

Mockpopen multiple processes

---

testfixtures/comparison.py
testfixtures/compat.py

When using the `testfixtures` package in a python 3.7 environment, deprecation warnings are visible:
```
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
```
Also see the note about `Changed in version 3.3: Moved Collections Abstract Base Classes to the collections.abc module` at: https://docs.python.org/3.7/library/collections.html

Import `Iterable` from the non-deprecated location.

---

testfixtures/comparison.py
testfixtures/tests/test_compare.py

...in order to ensure cleaner output on compare() failures, by:
* Suppressing "While comparing: ..." addendum for recursed comparisons
* On Py2.7, stops object_compare from recursing into Decimal internals
Fixes #121

Add Decimal to the default comparer registry

---

testfixtures/comparison.py
testfixtures/tests/test_compare.py

compare(): Add support for naming x/y kwargs and document x/y_label kwargs

---

testfixtures/comparison.py
testfixtures/tests/test_comparison.py

...even in `strict` mode. (This was previously working before v6.0.0)
Fixes #122

Restore ability for Comparison() to compare properties (and methods)

---

docs/datetime.txt

The documentation is about the `testfxtures` module; remove confusing references to the class-like `TestFixtures` name.
Also fix the completely wrong references to `TestFixtures`.

Correct confusing name and fix typos

---

testfixtures/comparison.py
testfixtures/tests/test_compare.py

The object comparer indirectly relies on the ` __eq__` method of attributes in the check `x_attrs != y_attrs` even when ignore_eq is set.
This PR changes it to always compare the mappings when ignore_eq is enabled. I have also created a test case using the OrmObj object.
The test_compare.py passes on its own; however when I installed Django to run the other tests; I ran into this error using `pytest testfixtures/tests/test_django/test_compare.py`:
```
E   django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```
I am not sure how to run the tests properly.

Always compare object mappings when ignore_eq is enabled.

---

testfixtures/comparison.py

comparison.py:308: DeprecationWarning: invalid escape sequence \s

fix deprecation warning about invalid escape sequence

---

testfixtures/comparison.py
testfixtures/tests/test_mappingcomparison.py

`MappingComparison.__ne__` should return boolean result, not `None`

MappingComparison return type

---

testfixtures/compat.py
testfixtures/tests/test_popen.py
testfixtures/tests/test_replace.py

Hi,
Tests need a few small adjustments to pass with Python 3.10.
I guess you could add Python 3.10 it to your CI (and make it non-fatal) but I don't know how Circle CI works so I did not attempt to do it.

tests: fix with Python 3.10 (changed exception messages)

---

testfixtures/tests/test_comparison.py
testfixtures/tests/test_date.py
testfixtures/tests/test_datetime.py
testfixtures/tests/test_generator.py
testfixtures/tests/test_log_capture.py
testfixtures/tests/test_replace.py
testfixtures/tests/test_stringcomparison.py
testfixtures/tests/test_tempdir.py
testfixtures/tests/test_tempdirectory.py

Fixes #162 . The changes are mostly straightforward find and replace.
```
$ perl -pi -e 's/failIf/assertFalse/g' **/*py
$ perl -pi -e 's/failUnless/assertTrue/g' **/*py
```

Fix deprecated aliases for Python 3.11 compatibility.

---

docs/conftest.py
docs/django.txt
setup.py
testfixtures/tests/conftest.py

Hi, we are trying to enable packages for Python 3.10 in openSUSE Tumleweed. We need sybil 3 for that, but not being able to update testfixtures blocks it.
~AFAICT the rename of the CodeBlockParser was the only relevant change.~ Edit: Did not check the doctests. My bad.
New version of #166: Also allow older version for Python 2 support.

Use new sybil 3 name for codeblock parser if available

---

docs/warnings.txt
testfixtures/shouldwarn.py
testfixtures/tests/test_shouldwarn.py

Add ordered argument to ShouldWarn context manager

---

testfixtures/logcapture.py
testfixtures/tempdirectory.py

I found two places where type hints declare one item tuple instead of arbitrary-length tuple of strings (as indicated by docstring).

Fix tuple of strings type hints

---

testfixtures/replace.py
testfixtures/tests/test_replace.py

Replacing a method on a subclass rather than the base class ends up leaving the replacement there after restore.
Digging in to this uncovered a bunch of other sadness, so this deals with all of that.

Work for replacing where the original is somewhere interesting

---

.circleci/config.yml
mypy.ini
setup.py
testfixtures/__init__.py
testfixtures/comparison.py
testfixtures/datetime.py
testfixtures/django.py
testfixtures/logcapture.py
testfixtures/mock.py
testfixtures/popen.py
testfixtures/replace.py
testfixtures/resolve.py
testfixtures/shouldraise.py
testfixtures/shouldwarn.py
testfixtures/tempdirectory.py
testfixtures/tests/test_datetime.py
testfixtures/tests/test_replace.py
testfixtures/tests/test_should_raise.py
testfixtures/tests/test_tempdirectory.py
testfixtures/twisted.py
testfixtures/utils.py

The aim of this change is to check mypy running against pull requests and passing, even if it's in a super permissive way.
It should also enforce strict typing where possible, with the intention that newly added modules will be fully types and existing modules should eventually get there.

Initial steps towards full typing

---

docs/conf.py
mypy.ini
setup.py
testfixtures/__init__.py
testfixtures/comparison.py
testfixtures/datetime.py
testfixtures/django.py
testfixtures/logcapture.py
testfixtures/outputcapture.py
testfixtures/popen.py
testfixtures/replace.py
testfixtures/resolve.py
testfixtures/rmtree.py
testfixtures/shouldraise.py
testfixtures/shouldwarn.py
testfixtures/sybil.py
testfixtures/tempdirectory.py
testfixtures/twisted.py
testfixtures/utils.py

The aim of this pull request is to get to a point where non-strict mypy passes with `disallow_untyped_defs = True` and `disallow_incomplete_defs = True`, except in tests.
This should allow an experiment to see if it's safe/sane to ship a `testfixtures` release with a `py.typed` marker file.
Things to do:

More typing work

---

mypy.ini
testfixtures/outputcapture.py
testfixtures/tests/test_outputcapture.py
testfixtures/tests/test_stringcomparison.py

Add support for `StringComparison` as parameters to `OutputCapture.compare()`
